Load Balancer Simulation: main.cpp File Reference
main.cpp File Reference
Runs the load balancer simulation by generating requests and driving cycles.
#include <iostream>
#include <vector>
#include <cstdlib>
#include <ctime>
#include "loadBalancer.h"
#include "request.h"
Functions
std::string generateRandomIP ()
Generates a random IPv4 address string.
Request createRandomRequest ()
Creates a randomized Request with timing and job type.
int main ()
Entry point for the load balancer simulation.
Variables
const int MIN_TASK_TIME = 40
const int MAX_TASK_TIME = 99
Detailed Description
Runs the load balancer simulation by generating requests and driving cycles.
Definition in file main.cpp.
Function Documentation
createRandomRequest()
Request createRandomRequest ()
Creates a randomized Request with timing and job type.
Returns
Request populated with random IPs, duration, and job category.
Definition at line 32 of file main.cpp.
References generateRandomIP(), Request::ip_in, Request::ip_out, Request::job_type, MAX_TASK_TIME, MIN_TASK_TIME, and Request::time_to_process.
Referenced by main().
generateRandomIP()
std::string generateRandomIP ()
Generates a random IPv4 address string.
Returns
Randomly generated dotted-quad IP address.
Definition at line 21 of file main.cpp.
Referenced by createRandomRequest().
main()
int main ()
Entry point for the load balancer simulation.
Returns
Zero on successful execution.
Definition at line 47 of file main.cpp.
References LoadBalancer::addRequest(), createRandomRequest(), LoadBalancer::getQueueSize(), LoadBalancer::getTime(), LoadBalancer::logMessage(), MAX_TASK_TIME, MIN_TASK_TIME, LoadBalancer::performCycle(), and LoadBalancer::printStats().
Variable Documentation
MAX_TASK_TIME
const int MAX_TASK_TIME = 99
Definition at line 15 of file main.cpp.
Referenced by createRandomRequest(), and main().
MIN_TASK_TIME
const int MIN_TASK_TIME = 40
Definition at line 14 of file main.cpp.
Referenced by createRandomRequest(), and main().